# Generated by Django 5.0.7 on 2025-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_account_name_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
