# Generated by Django 5.0.7 on 2025-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_monthlytransactionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_condition',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
