# Generated by Django 5.0.7 on 2025-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
