# Generated by Django 5.0.7 on 2024-11-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_audio/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='episode_images/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcast'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
