# Generated by Django 5.0.7 on 2024-10-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_episode_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(null=True, upload_to='episode_images/'),
        ),
    ]
