# Generated by Django 5.0.7 on 2024-12-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_1',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_2',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
