# Generated by Django 5.0.7 on 2024-10-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_benefit_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
