# Generated by Django 5.0.7 on 2024-11-09 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetoxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('tabs', models.IntegerField(null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
            ],
        ),
        migrations.CreateModel(
            name='FortifyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=255, null=True)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('tabs', models.IntegerField(null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthSupportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condition', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
        migrations.CreateModel(
            name='Health_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('fortify', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.fortifyoption')),
                ('side_effect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.detoxoption')),
                ('health_support', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.healthsupportoption')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='NT_gallery.maincategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('sub_categories', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strength', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pictures', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('benefits', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='NT_gallery.health_benefits')),
            ],
        ),
        migrations.AddField(
            model_name='health_benefits',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.product'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='NT_gallery.product')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='NT_gallery.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='NT_gallery.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
    ]
