# Generated by Django 5.0.7 on 2024-11-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=255, null=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DosageForm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fortify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=255, null=True)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('tabs', models.IntegerField(null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Health_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condition', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LifestyleType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PharmacyGrouping', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortify', models.ManyToManyField(blank=True, related_name='products', to='NT_gallery.fortify')),
                ('health_support', models.ManyToManyField(blank=True, related_name='products', to='NT_gallery.health_support')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('sub_categories', models.JSONField(default=list, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pictures', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('health_benefit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='NT_gallery.health_benefits')),
            ],
        ),
        migrations.AddField(
            model_name='health_support',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='health_benefits',
            name='nutrient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='fortify',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='NT_gallery.product')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Side_effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=255, null=True)),
                ('tabs', models.IntegerField(null=True)),
                ('times_per_day', models.IntegerField(null=True)),
                ('length_of_use', models.CharField(max_length=255, null=True)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summary_doc/')),
                ('nutrient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product')),
            ],
        ),
        migrations.AddField(
            model_name='health_benefits',
            name='side_effect',
            field=models.ManyToManyField(blank=True, related_name='products', to='NT_gallery.side_effects'),
        ),
    ]
