# Generated by Django 5.0.7 on 2024-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0001_initial'),
        ('user', '0002_userprofile_preference_lifestyle_healthcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('60+', '60+'), ('50+', '50+'), ('40+', '40+'), ('Young Adults', 'Young Adults'), ('Adults', 'Adults'), ('Teens', 'Teens'), ('Children (General)', 'Children (General)'), ('Toddlers', 'Toddlers'), ('Infant', 'Infant')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[("Nature's Field", "Nature's Field"), ("Puritan's Pride", "Puritan's Pride"), ('Vitabiotics', 'Vitabiotics'), ('Centrum', 'Centrum'), ('Seven Seas', 'Seven Seas'), ('Reload', 'Reload'), ('Goli', 'Goli'), ('Olly', 'Olly'), ("Earth's Creation", "Earth's Creation"), ('Piping Rock', 'Piping Rock'), ('Solgar', 'Solgar'), ('Country Life', 'Country Life'), ("Mason's Natural", "Mason's Natural"), ('Garden of Life', 'Garden of Life'), ("Nature's Truth", "Nature's Truth"), ('Swanson', 'Swanson'), ('Emzor', 'Emzor'), ('M&B', 'M&B'), ('Force Factor', 'Force Factor'), ('Renew Life', 'Renew Life'), ('Elbe', 'Elbe'), ('Relumins', 'Relumins'), ('Nutrify', 'Nutrify'), ('Mega We Care', 'Mega We Care'), ('Winstown', 'Winstown'), ('Optibac', 'Optibac'), ('Holand & Barett', 'Holand & Barett'), ('Horbach', 'Horbach'), ('Himalaya', 'Himalaya'), ("Nature's Bounty", "Nature's Bounty"), ('Now', 'Now'), ('Organic Health', 'Organic Health'), ('Imedeen', 'Imedeen'), ('Renzo', 'Renzo'), ('Kirkland', 'Kirkland'), ('Haliborange', 'Haliborange'), ('Wholesome Foods', 'Wholesome Foods'), ('Max World', 'Max World'), ('Fafor Life', 'Fafor Life'), ('Super Life', 'Super Life'), ('Bayer', 'Bayer'), ('Dr. Meyer', 'Dr. Meyer'), ('Live Pure', 'Live Pure'), ('Gain World', 'Gain World'), ('21st Century', '21st Century'), ('Gaia', 'Gaia'), ("Doctor's Best", "Doctor's Best")], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Creams', 'Creams'), ('Gummies', 'Gummies'), ('Inhalers', 'Inhalers'), ('Patches', 'Patches'), ('Liquid', 'Liquid'), ('Powders', 'Powders'), ('Capsules', 'Capsules'), ('Tablets', 'Tablets')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('For Teen Girls', 'For Teen Girls'), ('For Teen Boys', 'For Teen Boys'), ('For Women', 'For Women'), ('For Men', 'For Men')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vitality', 'Vitality'), ('Immunity', 'Immunity'), ('Quick Recovery', 'Quick Recovery'), ('Brain Power (Wealth Creation)', 'Brain Power (Wealth Creation)'), ('Skin, Beauty, Graceful Ageing', 'Skin, Beauty, Graceful Ageing'), ('Longevity', 'Longevity')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Single Vitamins', 'Single Vitamins'), ('Multi Vitamins', 'Multi Vitamins'), ('Multi Minerals', 'Multi Minerals'), ('Herbal Supplements', 'Herbal Supplements'), ('Essential Fatty Acids', 'Essential Fatty Acids'), ('Amino Acids', 'Amino Acids'), ('Tonics', 'Tonics'), ('Nature Made', 'Nature Made'), ('Enzymes', 'Enzymes'), ('Probiotics', 'Probiotics'), ('Adaptogens', 'Adaptogens'), ('Antioxidants', 'Antioxidants')], max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suitable_for',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='benefits',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lifestyle_compatibility',
            new_name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='name',
            field=models.CharField(choices=[('For Sex Enthusiasts', 'For Sex Enthusiasts'), ('For Clubbers', 'For Clubbers'), ('For Smokers', 'For Smokers'), ('For Drinkers', 'For Drinkers'), ('Gym Enthusiasts', 'Gym Enthusiasts'), ('Skin and Fashion Lovers', 'Skin and Fashion Lovers'), ('Prayers and Spiritual Exercises (Meditation, Fasting, Yoga)', 'Prayers and Spiritual Exercises (Meditation, Fasting, Yoga)')], max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.ManyToManyField(to='NT_gallery.agegroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(to='NT_gallery.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.ManyToManyField(to='NT_gallery.dosageform'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(to='NT_gallery.gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='lifestyle_rating',
            field=models.ManyToManyField(to='NT_gallery.lifestylerating'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacy_grouping',
            field=models.ManyToManyField(to='NT_gallery.pharmacygrouping'),
        ),
        migrations.DeleteModel(
            name='HealthGoal',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
    ]
