# Generated by Django 5.0.7 on 2024-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lsv',
            field=models.JSONField(default=list),
        ),
    ]
