# Generated by Django 5.0.7 on 2024-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0002_agerange_brand_dosageform_gender_lifestylerating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Health_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Side_effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinical_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Health_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('Fortify', models.ManyToManyField(to='NT_gallery.fortify')),
                ('health_support', models.ManyToManyField(to='NT_gallery.health_support')),
                ('Side_effects', models.ManyToManyField(to='NT_gallery.side_effects')),
            ],
        ),
    ]
