# Generated by Django 5.0.7 on 2024-10-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0002_agegroup_brand_dosageform_gender_genderduplicate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenderDuplicate',
        ),
        migrations.RenameField(
            model_name='agegroup',
            old_name='name',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='Brand_Name',
        ),
        migrations.RenameField(
            model_name='dosageform',
            old_name='name',
            new_name='DosageForm',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='name',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='lifestyle',
            old_name='name',
            new_name='LifestyleType',
        ),
        migrations.RenameField(
            model_name='lifestylerating',
            old_name='name',
            new_name='LifestyleRating',
        ),
        migrations.RenameField(
            model_name='pharmacygrouping',
            old_name='name',
            new_name='PharmacyGrouping',
        ),
    ]
