# Generated by Django 5.0.7 on 2024-11-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0002_product_lsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='health_benefit',
        ),
    ]
