# Generated by Django 5.0.7 on 2024-11-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0003_remove_product_health_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lsv',
        ),
        migrations.CreateModel(
            name='LSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsvs', to='NT_gallery.product')),
            ],
        ),
    ]
