# Generated by Django 5.0.7 on 2024-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0003_fortify_health_support_side_effects_health_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='health_benefits',
            field=models.ManyToManyField(to='NT_gallery.health_benefits'),
        ),
    ]
