# Generated by Django 5.0.7 on 2024-12-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0003_alter_product_category_alter_product_lsvs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'LSVs',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='lsvs',
            field=models.ManyToManyField(blank=True, related_name='products', to='NT_gallery.lsv'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_condition',
            field=models.ManyToManyField(blank=True, related_name='products', to='NT_gallery.flag_condition'),
        ),
    ]
