# Generated by Django 5.0.7 on 2024-10-24 16:50

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0004_product_health_benefits'),
    ]

    operations = [
    ]
