# Generated by Django 5.0.7 on 2024-10-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0004_product_created_at_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='age_group',
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='Age',
            field=models.CharField(choices=[('70+', '60'), ('60+', '60+'), ('50+', '50+'), ('40+', '40+'), ('general', 'general'), ('Young Adults', 'Young Adults'), ('Adults', 'Adults'), ('Teens', 'Teens'), ('Children (General)', 'Children (General)'), ('Toddlers', 'Toddlers'), ('Infant', 'Infant')], max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='age_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.agerange'),
        ),
    ]
