# Generated by Django 5.0.7 on 2024-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0004_flag_condition_alter_product_lsvs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag_condition',
            options={'verbose_name_plural': 'Flag conditions'},
        ),
    ]
