# Generated by Django 5.0.7 on 2024-10-24 16:50

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0004_product_health_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='Product',
            name='age_range',
            field= models.ForeignKey(on_delete= models.CASCADE, related_name='product', to='NT_gallery.agerange')
        )
    ]
