# Generated by Django 5.0.7 on 2024-10-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0005_auto_20241024_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.agerange'),
        ),
    ]
