# Generated by Django 5.0.7 on 2024-11-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0005_remove_lsv_product_product_lsvs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lsv',
            options={'verbose_name_plural': 'LSVs'},
        ),
    ]
