# Generated by Django 5.0.7 on 2024-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0005_alter_flag_condition_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='product_images/'),
        ),
    ]
