# Generated by Django 5.0.7 on 2025-01-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0006_remove_product_pictures_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosageform',
            name='DosageForm',
        ),
        migrations.AddField(
            model_name='dosageform',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_form', to='NT_gallery.dosageform'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='product_image/'),
        ),
    ]
