# Generated by Django 5.0.7 on 2024-10-26 13:04

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0006_alter_product_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.IntegerField(blank=True, null=True)
            )
    ]
