# Generated by Django 5.0.7 on 2024-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0007_auto_20241026_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Generic_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
