# Generated by Django 5.0.7 on 2024-10-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0008_product_generic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_support',
            old_name='name',
            new_name='health_condition',
        ),
        migrations.RenameField(
            model_name='side_effects',
            old_name='name',
            new_name='medication',
        ),
        migrations.RemoveField(
            model_name='fortify',
            name='name',
        ),
        migrations.RemoveField(
            model_name='health_benefits',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='health_benefits',
        ),
        migrations.AddField(
            model_name='fortify',
            name='length_of_use',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fortify',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='fortify',
            name='organ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fortify',
            name='strength',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fortify',
            name='tabs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fortify',
            name='times_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='health_benefits',
            name='nutrient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='health_support',
            name='length_of_use',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health_support',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='health_support',
            name='strength',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='health_support',
            name='times_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='side_effects',
            name='length_of_use',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='side_effects',
            name='nutrient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NT_gallery.product'),
        ),
        migrations.AddField(
            model_name='side_effects',
            name='strength',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='side_effects',
            name='tabs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='side_effects',
            name='times_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fortify',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summary_doc/'),
        ),
        migrations.AlterField(
            model_name='health_support',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summary_doc/'),
        ),
        migrations.AlterField(
            model_name='side_effects',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summary_doc/'),
        ),
    ]
