# Generated by Django 5.0.7 on 2024-10-29 18:18

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0009_rename_name_health_support_health_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleRating',
            fields=[
                ('LifestyleRating', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
