# Generated by Django 5.0.7 on 2024-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0010_auto_20241029_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lifestyle_rating',
        ),
        migrations.DeleteModel(
            name='LifestyleRating',
        ),
    ]
