# Generated by Django 5.0.7 on 2024-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0012_lifestylerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifestyle_rating',
            field=models.ManyToManyField(to='NT_gallery.lifestylerating'),
        ),
    ]
