# Generated by Django 5.0.7 on 2024-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0014_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_benefits',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
