# Generated by Django 5.0.7 on 2024-10-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0016_remove_health_benefits_fortify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_benefits',
            name='Fortify',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.fortify'),
        ),
        migrations.AlterField(
            model_name='health_benefits',
            name='Side_effects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.side_effects'),
        ),
        migrations.AlterField(
            model_name='health_benefits',
            name='health_support',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_benefits', to='NT_gallery.health_support'),
        ),
    ]
