# Generated by Django 5.0.7 on 2024-11-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0017_alter_health_benefits_fortify_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='lifestyle_rating',
        # ),
        # migrations.DeleteModel(
        #     name='LifestyleRating',
        # ),
    ]
