# Generated by Django 5.0.7 on 2024-11-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0018_remove_product_lifestyle_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LifestyleRating', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='lifestyle_rating',
            field=models.ManyToManyField(to='NT_gallery.lifestylerating'),
        ),
    ]
