# Generated by Django 5.0.7 on 2024-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='budget',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
