# Generated by Django 5.0.7 on 2024-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_basic_budget_userprofile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
