# Generated by Django 5.0.7 on 2024-10-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_preference_lifestyle_healthcondition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basics',
            new_name='Basic',
        ),
    ]
