# Generated by Django 5.0.7 on 2024-11-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NT_gallery', '0001_initial'),
        ('user', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='NT_gallery.product'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.message'),
        ),
    ]
