# Generated by Django 5.0.7 on 2024-11-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='new_msg',
        ),
    ]
